#基础配置
#端口号
server:
  port: 8089
  servlet:
    context-path: /song

spring:
#  mysql连接配置
  datasource:
    username: root
    password: Admin123
    url: jdbc:mysql://127.0.0.1:3306/springboot_test?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

# redis连接配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0
  #  qq邮件配置
  mail:
    username: 2548533500@qq.com
    # 邮箱生成的校验码
    password: xzhpkkoefyqkdjbi
    host: smtp.qq.com
    port: 465
    default-encoding: utf-8
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  #不检索thymeleaf模板引擎
  thymeleaf:
    check-template: false
    check-template-location: false
#mybatis配置
mybatis:
  # type-aliases-package批量设置别名作用：在mapper.xml文件中直接写类名，不配置则需要写类的全路径名
  type-aliases-package: com.example.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml

#将 mapper 日志级别设置为 "debug "
logging:
  level:
    com.example.mapper: debug

# 系统参数
system-parameters:
  thread-pool:
#    核心线程数
    corePoolSize: 3
#    最大线程数
    maxPoolSize: 6
#    空闲线程存活时间
    keepAliveSeconds: 10
#    队列大小
    queueCapactiy: 3
  # 定时任务 cron 表达式
  scheduling:
    # 每 2分钟执行一次
    user: 0 0/2 * * * ?
    # 每 1分钟执行一次
    grade: 0 0/1 * * * ?
  #配置RocketMQ参数
  rocketmq:
    ipPort: 127.0.0.1:9876
    topic: ROCKETMQ_SONG_TOPIC
    gd_produce_group: ROCKETMQ_SONG_TOPIC
  cache:
#   缓存最大值
    max_size: 500
#   缓存时间（秒）
    cache_time: 500
  # 异常用户处理后是否发送邮件通知
  is_send_email: false

#配置钉钉参数
dingding-parmeters:
  #  手机号
  dingding_mobiles: 15656112757
  #  钉钉URL
  dingding_api_url: https://oapi.dingtalk.com/robot/send?access_token=8bc63dde817067241c978977cbff64168db667ad14eb4ccb4eb744d612da280c
